// proto/node_control.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/node_control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeControl_Ping_FullMethodName         = "/proto.NodeControl/Ping"
	NodeControl_RegisterNode_FullMethodName = "/proto.NodeControl/RegisterNode"
)

// NodeControlClient is the client API for NodeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeControlClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type nodeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlClient(cc grpc.ClientConnInterface) NodeControlClient {
	return &nodeControlClient{cc}
}

func (c *nodeControlClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeControl_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) RegisterNode(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NodeControl_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeControlServer is the server API for NodeControl service.
// All implementations must embed UnimplementedNodeControlServer
// for forward compatibility.
type NodeControlServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	RegisterNode(context.Context, *NodeInfo) (*RegisterResponse, error)
	mustEmbedUnimplementedNodeControlServer()
}

// UnimplementedNodeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServer struct{}

func (UnimplementedNodeControlServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeControlServer) RegisterNode(context.Context, *NodeInfo) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedNodeControlServer) mustEmbedUnimplementedNodeControlServer() {}
func (UnimplementedNodeControlServer) testEmbeddedByValue()                     {}

// UnsafeNodeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServer will
// result in compilation errors.
type UnsafeNodeControlServer interface {
	mustEmbedUnimplementedNodeControlServer()
}

func RegisterNodeControlServer(s grpc.ServiceRegistrar, srv NodeControlServer) {
	// If the following call pancis, it indicates UnimplementedNodeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControl_ServiceDesc, srv)
}

func _NodeControl_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).RegisterNode(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeControl_ServiceDesc is the grpc.ServiceDesc for NodeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NodeControl",
	HandlerType: (*NodeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NodeControl_Ping_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _NodeControl_RegisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/node_control.proto",
}
