// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ping_pong.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	HandshakeId   string                 `protobuf:"bytes,3,opt,name=handshake_id,json=handshakeId,proto3" json:"handshake_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_ping_pong_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ping_pong_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ping_pong_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PingRequest) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *PingRequest) GetHandshakeId() string {
	if x != nil {
		return x.HandshakeId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_ping_pong_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ping_pong_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ping_pong_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListenPort    int32                  `protobuf:"varint,2,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	HandshakeId   string                 `protobuf:"bytes,3,opt,name=handshake_id,json=handshakeId,proto3" json:"handshake_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongRequest) Reset() {
	*x = PongRequest{}
	mi := &file_proto_ping_pong_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongRequest) ProtoMessage() {}

func (x *PongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ping_pong_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongRequest.ProtoReflect.Descriptor instead.
func (*PongRequest) Descriptor() ([]byte, []int) {
	return file_proto_ping_pong_proto_rawDescGZIP(), []int{2}
}

func (x *PongRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PongRequest) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *PongRequest) GetHandshakeId() string {
	if x != nil {
		return x.HandshakeId
	}
	return ""
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_proto_ping_pong_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ping_pong_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_proto_ping_pong_proto_rawDescGZIP(), []int{3}
}

func (x *PongResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ping_pong_proto protoreflect.FileDescriptor

const file_proto_ping_pong_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ping_pong.proto\x12\x05swarm\"a\n" +
	"\vPingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12!\n" +
	"\fhandshake_id\x18\x03 \x01(\tR\vhandshakeId\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"a\n" +
	"\vPongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vlisten_port\x18\x02 \x01(\x05R\n" +
	"listenPort\x12!\n" +
	"\fhandshake_id\x18\x03 \x01(\tR\vhandshakeId\"(\n" +
	"\fPongResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2l\n" +
	"\bPingPong\x12/\n" +
	"\x04Ping\x12\x12.swarm.PingRequest\x1a\x13.swarm.PingResponse\x12/\n" +
	"\x04Pong\x12\x12.swarm.PongRequest\x1a\x13.swarm.PongResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_ping_pong_proto_rawDescOnce sync.Once
	file_proto_ping_pong_proto_rawDescData []byte
)

func file_proto_ping_pong_proto_rawDescGZIP() []byte {
	file_proto_ping_pong_proto_rawDescOnce.Do(func() {
		file_proto_ping_pong_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ping_pong_proto_rawDesc), len(file_proto_ping_pong_proto_rawDesc)))
	})
	return file_proto_ping_pong_proto_rawDescData
}

var file_proto_ping_pong_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ping_pong_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: swarm.PingRequest
	(*PingResponse)(nil), // 1: swarm.PingResponse
	(*PongRequest)(nil),  // 2: swarm.PongRequest
	(*PongResponse)(nil), // 3: swarm.PongResponse
}
var file_proto_ping_pong_proto_depIdxs = []int32{
	0, // 0: swarm.PingPong.Ping:input_type -> swarm.PingRequest
	2, // 1: swarm.PingPong.Pong:input_type -> swarm.PongRequest
	1, // 2: swarm.PingPong.Ping:output_type -> swarm.PingResponse
	3, // 3: swarm.PingPong.Pong:output_type -> swarm.PongResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ping_pong_proto_init() }
func file_proto_ping_pong_proto_init() {
	if File_proto_ping_pong_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ping_pong_proto_rawDesc), len(file_proto_ping_pong_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ping_pong_proto_goTypes,
		DependencyIndexes: file_proto_ping_pong_proto_depIdxs,
		MessageInfos:      file_proto_ping_pong_proto_msgTypes,
	}.Build()
	File_proto_ping_pong_proto = out.File
	file_proto_ping_pong_proto_goTypes = nil
	file_proto_ping_pong_proto_depIdxs = nil
}
